#!/bin/bash

timestamp () {
  date +"%y%m%d%H%M%S"
}

LOG_PATH="/var/log/rsync_backup/"
NETWORK_LOG="${LOG_PATH}$(timestamp)-network.log"

if [ ! -d $LOG_PATH ]; then
  mkdir $LOG_PATH
fi

# Sichere alle Daten auf dem Server
rsync -auz /home/daniel/documents root@freenas:/mnt/backup-pool --exclude="node_modules" --log-file=$NETWORK_LOG